### ISSUE TITLE
Solution Link Dead - Exercise 1.1: Using the bigip_device_facts module 

### ISSUE THREAD

**Issue by zollerp** [f5alliances/ansible-use-cases-101#12]
Hi Team,

the Link belwo the "Solution Section" of "Exercise 1.1: Using the bigip_device_facts module" (https://github.com/f5alliances/ansible-use-cases-101/tree/master/1.1-get-facts) is dead:

Section:
#####
Solution
The finished Ansible Playbook is provided here for an Answer key. Click here for bigip-facts.yml.
#####
Click here for bigip-facts.yml. brings me to "https://github.com/f5alliances/ansible-use-cases-101/blob/master/bigip-facts.yml" with a 404

**Comment by zollerp** [comment]
Maybe this link was mentioned:
https://github.com/ansible/workshops/blob/master/exercises/ansible_f5/1.1-get-facts/bigip-facts.yml

**Comment by zollerp** [comment]
Prssed wrong button...sorry

**Comment by gwolfis** [comment]
the link has been fixed
