### ISSUE TITLE
wrong link to slack chat channel

### ISSUE THREAD

**Issue by pcloup** [f5alliances/ansible-use-cases-101#7]
the link in the following page : https://github.com/f5alliances/ansible-use-cases-101/tree/master/1.0-explore for slack is incorrect and points to an error page on SLACK.

**Comment by gwolfis** [comment]
Thanks for checking the content!
Currently checking if the link should stay and pointing to the right Slack Channel or if we want to point to a Team channel for the students.

**Comment by gwolfis** [comment]
Documentation has been fixed
