### ISSUE TITLE
link to LinuxAccademy

### ISSUE THREAD

**Issue by pcloup** [f5alliances/ansible-use-cases-101#8]
COSMETIC ISSUE: 
the link to LinuxAcademy on ANSIBLE basics should open in a new browser and not inside the actual browser session

**Comment by gwolfis** [comment]
Thanks for bringing this up.

According to this [article](https://github.community/t5/How-to-use-Git-and-GitHub/Can-t-get-links-to-open-in-new-tab-bis/td-p/28739) there is no solution to include this behavior into Markdown.

The workaround is to right-click and select "Open Link in New Tab"
