### ISSUE TITLE
Discussion Link on DevCentral

### ISSUE THREAD

**Issue by zollerp** [f5alliances/ansible-use-cases-101#9]
Hi Team,

withing "https://github.com/f5alliances/ansible-use-cases-101/blob/master/README.md" we got a section called: "To start a discussion or to post a question related to the workshop use link" The Link brings me to a general Question Section (https://devcentral.f5.com/s/questions) rather to (https://devcentral.f5.com/questions/f5-ansible-automation-discussion-63579).

Could you please check?
Thanks
Patrick

**Comment by gwolfis** [comment]
Link has been changed to file a Github issue instead
